#
# Playbook for deploy simple frontend project
#
# exra-vars:
# project - project name
# tarballs - tarballs count (old releases)

- hosts: all
  user: "{{ project }}"

  vars:
    projectName: "{{ project }}"
    user: "{{ project }}"
    type: "{{ build_type }}"

  tasks:
    - name: Set username
      set_fact:
        remote_user: "{{ user }}"

    - name: Copy static build to prod directory
      synchronize:
        src: ./storybook-static/
        dest: /var/www/{{ projectName }}/cs/releases/{{ansible_date_time.date}}-{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=.git"
          - "--exclude=deploy.yml"
          - "--exclude=.gitlab-ci.yml"
      when: type == 'static'

    - name: Save last deployed release path
      shell: basename $(readlink -f "/var/www/{{ projectName }}/cs/current")
      register: lastReleaseName

    - name: Remove old symlink
      shell: |
        rm -f /var/www/{{ projectName }}/cs/current

    - name: Make symlink for new prod
      shell: |
        mkdir -p /var/www/{{ projectName }}/cs/shared
        ln -s /var/www/{{ projectName }}/cs/releases/{{ansible_date_time.date}}-{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}} /var/www/{{ projectName }}/cs/current

    - name: Clean old release path
      file:
        state: absent
        path: "/var/www/{{ projectName }}/cs/releases/{{ lastReleaseName.stdout }}"
      register: deleteResult
